# Generated by Django 3.2 on 2021-04-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='author',
            new_name='recruiter',
        ),
    ]
