# Generated by Django 3.2 on 2021-04-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='stipend',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
