# Generated by Django 3.2 on 2021-04-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobpost_stipend'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='additional_info',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
